fix build with features enabled (#178)
Since 8817762d7b8f5cd10886147b828f95d19dc2a80a, build fails with any
features enabled..

error[E0308]: mismatched types
  --> src/main.rs:95:30
   |
95 |         match_output(format, &languages);
   |                              ^^^^^^^^^^
   |                              |
   |                              expected struct `tokei::Languages`, found reference
   |                              help: consider removing the borrow: `languages`
   |
   = note: expected type `tokei::Languages`
              found type `&tokei::Languages`

Problem is that when no features enabled, match_output() doesn't need
to "eat" `tokei::Languages`, but in real version of match_output it
must not be borrowed.

Fixes: https://github.com/Aaronepower/tokei/issues/177
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>