Fix clap errors
thread 'main' (739870) panicked at src/cli.rs:323:22:
Mismatch between definition and access of `file_input`. Could not downcast to &str, need to downcast to alloc::string::String

thread 'main' (740008) panicked at src/cli.rs:292:14:
Mismatch between definition and access of `streaming`. Could not downcast to &str, need to downcast to alloc::string::String